services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: shivsetu-backend
    restart: always
    ports:
      - "5001:5000"
    env_file:
      - ./backend/.env

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: shivsetu-admin
    restart: always
    ports:
      - "3001:80"
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: shivsetu-frontend
    restart: always
    ports:
      - "3002:80"
    depends_on:
      - backend