server {
    listen 80;
    listen [::]:80;

    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Admin static assets
    location /assets/ {
        try_files $uri =404;
    }

    # React SPA routes
    location / {
        try_files $uri $uri/ /index.html;
    }
}