name: Deploy ShivSetu

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy ShivSetu to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e

            cd /root/shivsetu/shivsetu

            echo "Pulling latest code..."
            git pull origin main

            echo "Building ShivSetu..."
            docker compose build

            echo "Starting ShivSetu..."
            docker compose up -d

            echo "Checking containers..."
            docker ps

            echo "Deployment completed!"
